# Generated by Django 5.1.4 on 2024-12-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(limit_choices_to={'status': 'A'}, to='schoolapp.course'),
        ),
    ]
